upload test result

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,6 +12,9 @@ jobs:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: circleci-demo
     working_directory: /go/src/github.com/ducngocvnk57/circleci-demo
+    environment:
+      TEST_RESULTS: /tmp/test-results
+
     steps:
       - checkout
       - restore_cache:
@@ -26,7 +29,7 @@ jobs:
             - vendor/
             - glide.lock
       - run:
-           name: Waiting for mysql to be ready
+          name: Waiting for mysql to be ready
           command: |
             for i in `seq 1 10`;
             do
@@ -36,7 +39,18 @@ jobs:
             done
             echo Failed waiting for mysql && exit 1
       - run: goose -dir migrations $DB_DRIVER $DB_DNS up
-      - run: make test
+      - run: mkdir -p $TEST_RESULTS
+      - run: go get -u github.com/jstemmer/go-junit-report
+      - run: 
+          name: Run unit tests
+          command: |
+            set -ou pipefail
+            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
+            # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
+            # without this option script will return success regardless of testing result due to pipe after test command
+            make test | tee ${TEST_RESULTS}/go-test.out
+      - store_test_results:
+          path: /tmp/test-results
   deploy-prod:
     docker:
       - image: 727429285764.dkr.ecr.us-west-2.amazonaws.com/primary_image
